version: "3.8"

x-python-service:
    &python-service
    build:
        context: ./setup/python-service
        args:
            - PROJECT_PATH=$PROJECT_PATH
    restart: always
    tty: true
    volumes:
        - ./app:$PROJECT_PATH/app
        - ./pyproject.toml:$PROJECT_PATH/pyproject.toml
        - ./.env:$PROJECT_PATH/.env
    env_file: .envconfig

services:

    dashboard-uvicorn:
        <<: *python-service
        depends_on:
            - postgres
        ports:
            - "48000:48000"
        command:
            - /bin/bash
            - -c
            - |
                source ./.venv/bin/activate &&
                poetry install --no-root &&
                cd app &&
                uvicorn main:app --port 48000

    celery-beat:
        << : *python-service
        depends_on:
            - rabbitmq
            - celery-worker
            - postgres
        command:
            - /bin/bash
            - -c
            - |
                source ./.venv/bin/activate &&
                poetry install --no-root &&
                cd app &&
                celery -A tasks beat

    celery-worker:
        << : *python-service
        depends_on:
            - rabbitmq
            - postgres
        command:
            - /bin/bash
            - -c
            - |
                source ./.venv/bin/activate &&
                poetry install --no-root &&
                cd app &&
                celery -A tasks worker

    rabbitmq:
        build:
            context: ./setup/rabbitmq
        ports:
            - "45672:45672"
        volumes:
            # - ./config/rabbitmq/rabbitmq.conf.template:/etc/rabbitmq/rabbitmq.conf.template
            - ./setup/rabbitmq/rabbitmq.conf.template:$PROJECT_PATH/setup/rabbitmq/rabbitmq.conf.template
        env_file: .env

    postgres:
        image: postgres:16.1-alpine3.18
        restart: always
        ports:
            - "45432:45432"
        env_file: .env

