version: "3.8"

x-python-service:
    &python-service
    build:
        context: ./dockerfiles/python
        args:
            - PROJECT_PATH=$PROJECT_PATH
    tty: true
    volumes:
        - ./app:$PROJECT_PATH/app
        - ./pyproject.toml:$PROJECT_PATH/pyproject.toml
        - ./.env:$PROJECT_PATH/.env
    env_file: .env

services:

    celery-beat:
        << : *python-service
        depends_on:
            - celery-worker
        command:
            - /bin/bash
            - -c
            - |
                source ./.venv/bin/activate &&
                poetry install --no-root &&
                cd app &&
                celery -A tasks beat

    celery-worker:
        << : *python-service
        command:
            - /bin/bash
            - -c
            - |
                source ./.venv/bin/activate &&
                poetry install --no-root &&
                cd app &&
                celery -A tasks worker