version: "3.8"

x-python-service:
    &python-service
    build:
        context: ./config/python-service
        args:
            - PROJECT_PATH=$PROJECT_PATH
    tty: true
    volumes:
        - ./app:$PROJECT_PATH/app
        - ./pyproject.toml:$PROJECT_PATH/pyproject.toml
        - ./.env:$PROJECT_PATH/.env
    env_file: .env

services:

    dashboard-uvicorn:
        <<: *python-service
        ports:
            - "48000:48000"
        command:
            - /bin/bash
            - -c
            - |
                source ./.venv/bin/activate &&
                poetry install --no-root &&
                cd app &&
                uvicorn main:app --port 48000

    celery-beat:
        << : *python-service
        depends_on:
            - rabbitmq
            - celery-worker
        command:
            - /bin/bash
            - -c
            - |
                source ./.venv/bin/activate &&
                poetry install --no-root &&
                cd app &&
                celery -A tasks beat

    celery-worker:
        << : *python-service
        depends_on:
            - rabbitmq
        command:
            - /bin/bash
            - -c
            - |
                source ./.venv/bin/activate &&
                poetry install --no-root &&
                cd app &&
                celery -A tasks worker

    rabbitmq:
        build:
            context: ./config/rabbitmq
        ports:
            - "45672:45672"
        volumes:
            - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        env_file: .env
